name: Deploy Astro to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Hacer checkout del repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # 3️⃣ Build de Astro con variables de entorno
      - name: Build Astro site
        env:
          PUBLIC_GOOGLE_CLIENT_ID: ${{ secrets.PUBLIC_GOOGLE_CLIENT_ID }}
          PUBLIC_VITE_BACKEND_URL: ${{ secrets.PUBLIC_VITE_BACKEND_URL }}
        run: npm run build

      # 4️⃣ Guardar el build como artifact (opcional, útil si quieres usarlo en otro job)
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: astro-build
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Descargar el artifact del build
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: astro-build
          path: dist

      # 2️⃣ Deploy a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
